version: '3.8'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB


  chat-service:
    build:
      context: .
      dockerfile: chat-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      GEMINI_API_KEY: $GEMINI_API_KEY
      HOST: $HOST
      PORT: $SERVICE_PORT
      JWT_SECRET: $JWT_SECRET
      USER_ID: $USID # Temporary, will be removed later