version: '3.8'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    environment:
      DBHOST: $DBHOST
      DBPORT: $DBPORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  chat-service:
    build:
      context: .
      dockerfile: chat-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      GEMINI_API_KEY: $GEMINI_API_KEY
      SERVER_HOST: $SERVER_HOST
      SERVER_PORT: $SERVER_PORT
      JWT_KEY: $JWT_KEY
      USER_ID: $USER_ID # Temporary, will be removed later
      DBHOST: $DBHOST
      DBPORT: $DBPORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
