version: '3.8'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB


  chat-service:
    build:
      context: .
      dockerfile: chat-service.dockerfile
    restart: always
    ports:
      - "8080:8080"